server:
  port: 8001

# MyBatis配置
mybatis:
  type-aliases-package: com.geekbyte.springcloud.Entity
#  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
#  configuration:
#    map-underscore-to-camel-case: true
#  mapper-locations: /home/cyp/github/Spring-Cloud-HelloWorld/springcloud-provider-dept-8001/src/main/resources/mybatis/mapper/*.xml
#  config-location: /home/cyp/github/Spring-Cloud-HelloWorld/springcloud-provider-dept-8001/src/main/resources/mybatis/mybatis-config.xml

# Spring配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud_d01?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: nihao2019